
const courses = [
  { id: 'dekiru', name: 'Dekiru Nihongo Sơ cấp', description: 'Học từ vựng theo các bài học trong giáo trình' },
  { id: 'jlpt5', name: 'Luyện thi JLPT N5', description: 'Các từ vựng cốt lõi ôn thi JLPT N5 phân theo chủ đề' }
];

const hiraganaData = [
  { kana: 'あ', romaji: 'a' }, { kana: 'い', romaji: 'i' }, { kana: 'う', romaji: 'u' }, { kana: 'え', romaji: 'e' }, { kana: 'お', romaji: 'o' },
  { kana: 'か', romaji: 'ka' }, { kana: 'き', romaji: 'ki' }, { kana: 'く', romaji: 'ku' }, { kana: 'け', romaji: 'ke' }, { kana: 'こ', romaji: 'ko' },
  { kana: 'さ', romaji: 'sa' }, { kana: 'し', romaji: 'shi' }, { kana: 'す', romaji: 'su' }, { kana: 'せ', romaji: 'se' }, { kana: 'そ', romaji: 'so' },
  { kana: 'た', romaji: 'ta' }, { kana: 'ち', romaji: 'chi' }, { kana: 'つ', romaji: 'tsu' }, { kana: 'て', romaji: 'te' }, { kana: 'と', romaji: 'to' },
  { kana: 'な', romaji: 'na' }, { kana: 'に', romaji: 'ni' }, { kana: 'ぬ', romaji: 'nu' }, { kana: 'ね', romaji: 'ne' }, { kana: 'の', romaji: 'no' },
  { kana: 'は', romaji: 'ha' }, { kana: 'ひ', romaji: 'hi' }, { kana: 'ふ', romaji: 'fu' }, { kana: 'へ', romaji: 'he' }, { kana: 'ほ', romaji: 'ho' },
  { kana: 'ま', romaji: 'ma' }, { kana: 'み', romaji: 'mi' }, { kana: 'む', romaji: 'mu' }, { kana: 'め', romaji: 'me' }, { kana: 'も', romaji: 'mo' },
  { kana: 'や', romaji: 'ya' }, { kana: '', romaji: '' }, { kana: 'ゆ', romaji: 'yu' }, { kana: '', romaji: '' }, { kana: 'よ', romaji: 'yo' },
  { kana: 'ら', romaji: 'ra' }, { kana: 'り', romaji: 'ri' }, { kana: 'る', romaji: 'ru' }, { kana: 'れ', romaji: 're' }, { kana: 'ろ', romaji: 'ro' },
  { kana: 'わ', romaji: 'wa' }, { kana: '', romaji: '' }, { kana: '', romaji: '' }, { kana: '', romaji: '' }, { kana: 'を', romaji: 'wo' },
  { kana: 'ん', romaji: 'n' }
];

const katakanaData = [
  { kana: 'ア', romaji: 'a' }, { kana: 'イ', romaji: 'i' }, { kana: 'ウ', romaji: 'u' }, { kana: 'エ', romaji: 'e' }, { kana: 'オ', romaji: 'o' },
  { kana: 'カ', romaji: 'ka' }, { kana: 'キ', romaji: 'ki' }, { kana: 'ク', romaji: 'ku' }, { kana: 'ケ', romaji: 'ke' }, { kana: 'コ', romaji: 'ko' },
  { kana: 'サ', romaji: 'sa' }, { kana: 'シ', romaji: 'shi' }, { kana: 'ス', romaji: 'su' }, { kana: 'セ', romaji: 'se' }, { kana: 'ソ', romaji: 'so' },
  { kana: 'タ', romaji: 'ta' }, { kana: 'チ', romaji: 'chi' }, { kana: 'ツ', romaji: 'tsu' }, { kana: 'テ', romaji: 'te' }, { kana: 'ト', romaji: 'to' },
  { kana: 'ナ', romaji: 'na' }, { kana: 'ニ', romaji: 'ni' }, { kana: 'ヌ', romaji: 'nu' }, { kana: 'ネ', romaji: 'ne' }, { kana: 'ノ', romaji: 'no' },
  { kana: 'ハ', romaji: 'ha' }, { kana: 'ヒ', romaji: 'hi' }, { kana: 'フ', romaji: 'fu' }, { kana: 'ヘ', romaji: 'he' }, { kana: 'ほ', romaji: 'ho' }, 
  { kana: 'マ', romaji: 'ma' }, { kana: 'ミ', romaji: 'mi' }, { kana: 'ム', romaji: 'mu' }, { kana: 'メ', romaji: 'me' }, { kana: 'モ', romaji: 'mo' },
  { kana: 'ヤ', romaji: 'ya' }, { kana: '', romaji: '' }, { kana: 'ユ', romaji: 'yu' }, { kana: '', romaji: '' }, { kana: 'ヨ', romaji: 'yo' },
  { kana: 'ラ', romaji: 'ra' }, { kana: 'リ', romaji: 'ri' }, { kana: 'ル', romaji: 'ru' }, { kana: 'レ', romaji: 're' }, { kana: 'ロ', romaji: 'ro' },
  { kana: 'ワ', romaji: 'wa' }, { kana: '', romaji: '' }, { kana: '', romaji: '' }, { kana: '', romaji: '' }, { kana: 'ヲ', romaji: 'wo' },
  { kana: 'ン', romaji: 'n' }
];

katakanaData[29].kana = 'ホ';

const vocabularyCategories = [

  {
    id: 'lesson1',
    courseId: 'dekiru',
    name: 'Bài 1: Hân hạnh gặp bạn',
    icon: '🤝',
    description: 'Từ vựng tự giới thiệu bản thân, quốc tịch, nghề nghiệp & sở thích',
    words: [
      { kanji: '私', kana: 'わたし', romaji: 'watashi', meaning: 'Tôi' },
      { kanji: '名前', kana: 'なまえ', romaji: 'namae', meaning: 'Tên' },
      { kanji: '国', kana: 'くに', romaji: 'kuni', meaning: 'Nước / Quốc gia' },
      { kanji: '日本', kana: 'にほん', romaji: 'nihon', meaning: 'Nhật Bản' },
      { kanji: 'アメリカ', kana: 'アメリカ', romaji: 'amerika', meaning: 'Nước Mỹ' },
      { kanji: 'イタリア', kana: 'イタリア', romaji: 'itaria', meaning: 'Nước Ý' },
      { kanji: 'オーストラリア', kana: 'オーストラリア', romaji: 'oosutoraria', meaning: 'Nước Úc' },
      { kanji: '韓国', kana: 'かんこく', romaji: 'kankoku', meaning: 'Hàn Quốc' },
      { kanji: 'タイ', kana: 'タイ', romaji: 'tai', meaning: 'Thái Lan' },
      { kanji: '中国', kana: 'ちゅうごく', romaji: 'chuugoku', meaning: 'Trung Quốc' },
      { kanji: 'ロシア', kana: 'ロシア', romaji: 'roshia', meaning: 'Nước Nga' },
      { kanji: '高校', kana: 'こうこう', romaji: 'koukou', meaning: 'Trường THPT' },
      { kanji: '大学', kana: 'だいがく', romaji: 'daigaku', meaning: 'Trường Đại học' },
      { kanji: '日本語学校', kana: 'にほんごがっこう', romaji: 'nihongogakkou', meaning: 'Trường tiếng Nhật' },
      { kanji: '仕事', kana: 'しごと', romaji: 'shigoto', meaning: 'Công việc' },
      { kanji: '学生', kana: 'がくせい', romaji: 'gakusei', meaning: 'Học sinh, sinh viên' },
      { kanji: '先生', kana: 'せんせい', romaji: 'sensei', meaning: 'Giáo viên' },
      { kanji: '教師', kana: 'きょうし', romaji: 'kyoushi', meaning: 'Giáo viên (tự xưng)' },
      { kanji: '会社員', kana: 'かいしゃいん', romaji: 'kaishain', meaning: 'Nhân viên công ty' },
      { kanji: 'どちら', kana: 'どちら', romaji: 'dochira', meaning: 'Ở đâu, hướng nào' },
      { kanji: 'はじめまして', kana: 'はじめまして', romaji: 'hajimemashite', meaning: 'Rất hân hạnh được gặp bạn' },
      { kanji: 'どうぞよろしく', kana: 'どうぞよろしく', romaji: 'douzo yoroshiku', meaning: 'Rất mong nhận được sự giúp đỡ' },
      { kanji: 'こちらこそ', kana: 'こちらこそ', romaji: 'kochira koso', meaning: 'Chính tôi mới là người cần giúp đỡ' },
      { kanji: 'すみません', kana: 'すみません', romaji: 'sumimasen', meaning: 'Xin lỗi / Cho hỏi thăm' },
      { kanji: 'そうですか', kana: 'そうですか', romaji: 'sou desu ka', meaning: 'Thế à? / Ra vậy' },
      { kanji: '誕生日', kana: 'たんじょうび', romaji: 'tanjoubi', meaning: 'Sinh nhật' },
      { kanji: 'いつ', kana: 'いつ', romaji: 'itsu', meaning: 'Khi nào' },
      { kanji: '趣味', kana: 'しゅみ', romaji: 'shumi', meaning: 'Sở thích' },
      { kanji: 'スポーツ', kana: 'スポーツ', romaji: 'supootsu', meaning: 'Thể thao' },
      { kanji: 'サッカー', kana: 'サッカー', romaji: 'sakkaa', meaning: 'Bóng đá' },
      { kanji: 'テニス', kana: 'テニス', romaji: 'tenisu', meaning: 'Quần vợt / Tennis' },
      { kanji: '水泳', kana: 'すいえい', romaji: 'suiei', meaning: 'Bơi lội' },
      { kanji: '映画', kana: 'えいが', romaji: 'eiga', meaning: 'Phim ảnh' },
      { kanji: '音楽', kana: 'おんがく', romaji: 'ongaku', meaning: 'Âm nhạc' },
      { kanji: '読書', kana: 'どくしょ', romaji: 'dokusho', meaning: 'Đọc sách' },
      { kanji: '旅行', kana: 'りょこう', romaji: 'ryokou', meaning: 'Du lịch' },
      { kanji: '料理', kana: 'りょうり', romaji: 'ryouri', meaning: 'Nấu ăn / Món ăn' }
    ]
  },
  {
    id: 'lesson2',
    courseId: 'dekiru',
    name: 'Bài 2: Mua sắm & Ăn uống',
    icon: '🛒',
    description: 'Từ vựng hỏi địa điểm, hỏi giá tiền, các loại hàng hóa & đồ ăn thức uống',
    words: [
      { kanji: 'ここ', kana: 'ここ', romaji: 'koko', meaning: 'Chỗ này / Ở đây' },
      { kanji: 'そこ', kana: 'そこ', romaji: 'soko', meaning: 'Chỗ kia / Ở đó' },
      { kanji: 'あそこ', kana: 'あそこ', romaji: 'asoko', meaning: 'Chỗ kìa / Ở kia' },
      { kanji: 'インフォメーション', kana: 'インフォメーション', romaji: 'infomeeshon', meaning: 'Quầy thông tin' },
      { kanji: 'ＡＴＭ', kana: 'エーティーエム', romaji: 'eetiiemu', meaning: 'Máy rút tiền ATM' },
      { kanji: 'エスカレーター', kana: 'エスカレーター', romaji: 'esukareetaa', meaning: 'Cầu thang cuốn' },
      { kanji: 'エレベーター', kana: 'エレベーター', romaji: 'erebeetaa', meaning: 'Thang máy' },
      { kanji: '喫煙所', kana: 'きつえんじょ', romaji: 'kitsuenjo', meaning: 'Khu vực hút thuốc' },
      { kanji: 'トイレ', kana: 'トイレ', romaji: 'toire', meaning: 'Nhà vệ sinh' },
      { kanji: 'レジ', kana: 'レジ', romaji: 'reji', meaning: 'Quầy thu ngân / Tính tiền' },
      { kanji: '喫茶店', kana: 'きっさてん', romaji: 'kissaten', meaning: 'Quán nước / Cà phê' },
      { kanji: 'スーパー', kana: 'スーパー', romaji: 'suupaa', meaning: 'Siêu thị' },
      { kanji: 'レストラン', kana: 'レストラン', romaji: 'resutoran', meaning: 'Nhà hàng' },
      { kanji: '地下', kana: 'ちか', romaji: 'chika', meaning: 'Dưới lòng đất / Tầng hầm' },
      { kanji: 'カメラ', kana: 'カメラ', romaji: 'kamera', meaning: 'Máy ảnh' },
      { kanji: '携帯電話', kana: 'けいたいだんわ', romaji: 'keitai denwa', meaning: 'Điện thoại di động' },
      { kanji: '電子辞書', kana: 'でんしじしょ', romaji: 'denshi jisho', meaning: 'Từ điển điện tử' },
      { kanji: 'パソコン', kana: 'パソコン', romaji: 'pasokon', meaning: 'Máy vi tính cá nhân' },
      { kanji: '靴', kana: 'くつ', romaji: 'kutsu', meaning: 'Giày, dép' },
      { kanji: '消しゴム', kana: 'けしゴム', romaji: 'keshigomu', meaning: 'Cục tẩy' },
      { kanji: 'ペン', kana: 'ペン', romaji: 'pen', meaning: 'Bút viết' },
      { kanji: 'トイレットペーパー', kana: 'トイレットペーパー', romaji: 'toirettopeepaa', meaning: 'Giấy vệ sinh' },
      { kanji: '本', kana: 'ほん', romaji: 'hon', meaning: 'Sách' },
      { kanji: 'ケーキ', kana: 'ケーキ', romaji: 'keeki', meaning: 'Bánh ngọt' },
      { kanji: '米', kana: 'こめ', romaji: 'kome', meaning: 'Gạo' },
      { kanji: '卵', kana: 'たまご', romaji: 'tamago', meaning: 'Trứng' },
      { kanji: 'パン', kana: 'パン', romaji: 'pan', meaning: 'Bánh mì' },
      { kanji: '水', kana: 'みず', romaji: 'mizu', meaning: 'Nước' },
      { kanji: '店員', kana: 'てんいん', romaji: 'tenin', meaning: 'Nhân viên bán hàng' },
      { kanji: 'どこ', kana: 'どこ', romaji: 'doko', meaning: 'Ở đâu' },
      { kanji: 'いらっしゃいませ', kana: 'いらっしゃいませ', romaji: 'irasshaimase', meaning: 'Xin kính chào quý khách' },
      { kanji: 'これ', kana: 'これ', romaji: 'kore', meaning: 'Cái này' },
      { kanji: 'それ', kana: 'それ', romaji: 'sore', meaning: 'Cái đó' },
      { kanji: 'あれ', kana: 'あれ', romaji: 'are', meaning: 'Cái kia' },
      { kanji: 'かばん', kana: 'かばん', romaji: 'kaban', meaning: 'Cặp, túi xách' },
      { kanji: 'ズボン', kana: 'ズボン', romaji: 'zubon', meaning: 'Cái quần' },
      { kanji: 'Ｔシャツ', kana: 'ティーシャツ', romaji: 'tiishatsu', meaning: 'Áo thun' },
      { kanji: '時計', kana: 'とけい', romaji: 'tokei', meaning: 'Đồng hồ' },
      { kanji: 'いくら', kana: 'いくら', romaji: 'ikura', meaning: 'Bao nhiêu tiền' },
      { kanji: '魚', kana: 'さかな', romaji: 'sakana', meaning: 'Cá' },
      { kanji: '肉', kana: 'にく', romaji: 'niku', meaning: 'Thịt' },
      { kanji: '牛肉', kana: 'ぎゅうにく', romaji: 'gyuuniku', meaning: 'Thịt bò' },
      { kanji: '鶏肉', kana: 'とりにく', romaji: 'toriniku', meaning: 'Thịt gà' },
      { kanji: '豚肉', kana: 'ぶたにく', romaji: 'butaniku', meaning: 'Thịt lợn' },
      { kanji: '野菜', kana: 'やさい', romaji: 'yasai', meaning: 'Rau củ' },
      { kanji: 'イチゴ', kana: 'イチゴ', romaji: 'ichigo', meaning: 'Quả dâu tây' },
      { kanji: 'リンゴ', kana: 'リンゴ', romaji: 'ringo', meaning: 'Quả táo' },
      { kanji: 'カレー', kana: 'カレー', romaji: 'karee', meaning: 'Món Cà ri' },
      { kanji: 'スープ', kana: 'スープ', romaji: 'suupu', meaning: 'Món súp' },
      { kanji: 'ご飯', kana: 'ごはん', romaji: 'gohan', meaning: 'Cơm / Bữa ăn' },
      { kanji: 'お茶', kana: 'おちゃ', romaji: 'ocha', meaning: 'Trà xanh' },
      { kanji: 'ジュース', kana: 'ジュース', romaji: 'juusu', meaning: 'Nước hoa quả' },
      { kanji: 'コーヒー', kana: 'コーヒー', romaji: 'koohii', meaning: 'Cà phê' },
      { kanji: '紅茶', kana: 'こうちゃ', romaji: 'koucha', meaning: 'Hồng trà / Trà đen' },
      { kanji: 'ビール', kana: 'ビール', romaji: 'biiru', meaning: 'Bia' },
      { kanji: 'ワイン', kana: 'ワイン', romaji: 'wain', meaning: 'Rượu vang' },
      { kanji: '英語', kana: 'えいご', romaji: 'eigo', meaning: 'Tiếng Anh' },
      { kanji: '誰', kana: 'だれ', romaji: 'dare', meaning: 'Ai' },
      { kanji: '注文をお願いします', kana: 'ちゅうもんをおねがいします', romaji: 'chuumon o onegai shimasu', meaning: 'Xin vui lòng cho tôi gọi món' },
      { kanji: '少々お待ちください', kana: 'しょうしょうおまちください', romaji: 'shoushou omachi kudasai', meaning: 'Xin chờ một lát' }
    ]
  },
  {
    id: 'lesson3',
    courseId: 'dekiru',
    name: 'Bài 3: Lịch trình & Sinh hoạt',
    icon: '📅',
    description: 'Từ vựng về thời gian, các địa điểm công cộng, hoạt động hàng ngày và động từ cơ bản',
    words: [
      { kanji: '今', kana: 'いま', romaji: 'ima', meaning: 'Bây giờ' },
      { kanji: '午前', kana: 'ごぜん', romaji: 'gozen', meaning: 'Sáng (AM)' },
      { kanji: '午後', kana: 'ごご', romaji: 'gogo', meaning: 'Chiều (PM)' },
      { kanji: '昼', kana: 'ひる', romaji: 'Buổi trưa' },
      { kanji: '銀行', kana: 'ぎんこう', romaji: 'ginkou', meaning: 'Ngân hàng' },
      { kanji: '体育館', kana: 'たいいくかん', romaji: 'taiikukan', meaning: 'Nhà thi đấu thể thao' },
      { kanji: '図書館', kana: 'としょかん', romaji: 'toshokan', meaning: 'Thư viện' },
      { kanji: '病院', kana: 'びょういん', romaji: 'byouin', meaning: 'Bệnh viện' },
      { kanji: '郵便局', kana: 'ゆうびんきょく', romaji: 'yuubinkyoku', meaning: 'Bưu điện' },
      { kanji: '授業', kana: 'じゅぎょう', romaji: 'jugyou', meaning: 'Giờ học' },
      { kanji: 'テスト', kana: 'テスト', romaji: 'tesuto', meaning: 'Bài thi / Kiểm tra' },
      { kanji: '休み', kana: 'やすみ', romaji: 'yasumi', meaning: 'Nghỉ ngơi' },
      { kanji: '時間', kana: 'じかん', romaji: 'jikan', meaning: 'Thời gian' },
      { kanji: 'スケジュール', kana: 'スケジュール', romaji: 'sukejuuru', meaning: 'Lịch trình' },
      { kanji: 'アルバイト', kana: 'アルバイト', romaji: 'arubaito', meaning: 'Việc làm thêm' },
      { kanji: 'スキー', kana: 'スキー', romaji: 'sukii', meaning: 'Trượt tuyết' },
      { kanji: 'パーティー', kana: 'パーティー', romaji: 'paatii', meaning: 'Bữa tiệc' },
      { kanji: 'バーベキュー', kana: 'バーベキュー', romaji: 'baabekyuu', meaning: 'Tiệc nướng BBQ' },
      { kanji: '花火', kana: 'はなび', romaji: 'hanabi', meaning: 'Pháo hoa' },
      { kanji: '花見', kana: 'はなみ', romaji: 'hanami', meaning: 'Ngắm hoa anh đào' },
      { kanji: 'ホームステイ', kana: 'ホームステイ', romaji: 'hoomusutei', meaning: 'Nhà người bản xứ (Homestay)' },
      { kanji: '祭り', kana: 'まつり', romaji: 'matsuri', meaning: 'Lễ hội' },
      { kanji: '海', kana: 'うみ', romaji: 'umi', meaning: 'Biển' },
      { kanji: '公園', kana: 'こうえん', romaji: 'kouen', meaning: 'Công viên' },
      { kanji: '桜', kana: 'さくら', romaji: 'sakura', meaning: 'Hoa anh đào' },
      { kanji: 'お酒', kana: 'おさけ', romaji: 'osake', meaning: 'Rượu' },
      { kanji: 'すし', kana: 'すし', romaji: 'sushi', meaning: 'Món Sushi' },
      { kanji: 'バス', kana: 'バス', romaji: 'basu', meaning: 'Xe buýt' },
      { kanji: 'お弁当', kana: 'おべんとう', romaji: 'obentou', meaning: 'Cơm hộp' },
      { kanji: '留学生', kana: 'りゅうがくせい', romaji: 'ryuugakusei', meaning: 'Du học sinh' },
      { kanji: '春', kana: 'はる', romaji: 'haru', meaning: 'Mùa xuân' },
      { kanji: '夏', kana: 'なつ', romaji: 'natsu', meaning: 'Mùa hè' },
      { kanji: '秋', kana: 'あき', romaji: 'aki', meaning: 'Mùa thu' },
      { kanji: '冬', kana: 'ふゆ', romaji: 'fuyu', meaning: 'Mùa đông' },
      { kanji: 'ゴールデンウィーク', kana: 'ゴールデンウィーク', romaji: 'goorudenwiiku', meaning: 'Tuần lễ vàng' },
      { kanji: '朝', kana: 'あさ', romaji: 'asa', meaning: 'Buổi sáng' },
      { kanji: '夜', kana: 'よる', romaji: 'yoru', meaning: 'Buổi tối / Đêm' },
      { kanji: '毎日', kana: 'まいにch', romaji: 'mainichi', meaning: 'Hàng ngày' },
      { kanji: '毎朝', kana: 'まいあさ', romaji: 'maiasa', meaning: 'Mỗi sáng' },
      { kanji: '毎晩', kana: 'まいばん', romaji: 'maiban', meaning: 'Mỗi tối' },
      { kanji: '朝ご飯', kana: 'あさごはん', romaji: 'asagohan', meaning: 'Cơm sáng' },
      { kanji: '昼ご飯', kana: 'ひるごはん', romaji: 'hirugohan', meaning: 'Cơm trưa' },
      { kanji: 'うち', kana: 'うち', romaji: 'uchi', meaning: 'Nhà mình' },
      { kanji: '会社', kana: 'かいしゃ', romaji: 'kaisha', meaning: 'Công ty' },
      { kanji: '学校', kana: 'がっこう', romaji: 'gakkou', meaning: 'Trường học' },
      { kanji: 'コンビニ', kana: 'コンビニ', romaji: 'konbini', meaning: 'Cửa hàng tiện lợi' },
      { kanji: '牛乳', kana: 'ぎゅうにゅう', romaji: 'gyuunyuu', meaning: 'Sữa bò' },
      { kanji: '果物', kana: 'くだもの', romaji: 'kudamono', meaning: 'Hoa quả' },
      { kanji: 'サラダ', kana: 'サラダ', romaji: 'sarada', meaning: 'Món sa-lát' },
      { kanji: 'チーズ', kana: 'チーズ', romaji: 'chiizu', meaning: 'Phô-mai' },
      { kanji: 'インターネット', kana: 'インターネット', romaji: 'intaanetto', meaning: 'Internet' },
      { kanji: '新聞', kana: 'しんぶん', romaji: 'shinbun', meaning: 'Báo giấy' },
      { kanji: 'テレビ', kana: 'テレビ', romaji: 'terebi', meaning: 'Tivi' },
      { kanji: '行きます', kana: 'いきます', romaji: 'ikimasu', meaning: 'Đi' },
      { kanji: '帰ります', kana: 'かえります', romaji: 'kaerimasu', meaning: 'Về (nhà, nước)' },
      { kanji: '飲みます', kana: 'のみます', romaji: 'nomimasu', meaning: 'Uống' },
      { kanji: '食べます', kana: 'たべます', romaji: 'tabemasu', meaning: 'Ăn' },
      { kanji: '見ます', kana: 'みます', romaji: 'mimasu', meaning: 'Xem' },
      { kanji: 'します', kana: 'します', romaji: 'shimasu', meaning: 'Làm / Chơi' },
      { kanji: '買います', kana: 'かいます', romaji: 'kaimasu', meaning: 'Mua' },
      { kanji: '聞きます', kana: 'ききます', romaji: 'kikimasu', meaning: 'Nghe' },
      { kanji: '働きます', kana: 'はたらきます', romaji: 'hatarakimasu', meaning: 'Làm việc' },
      { kanji: '読みます', kana: 'よみます', romaji: 'yomimasu', meaning: 'Đọc' },
      { kanji: '起きます', kana: 'おきます', romaji: 'okimasu', meaning: 'Thức dậy' },
      { kanji: '寝ます', kana: 'ねます', romaji: 'nemasu', meaning: 'Ngủ' },
      { kanji: '勉強します', kana: 'べんきょうします', romaji: 'benkyou shimasu', meaning: 'Học tập' },
      { kanji: '来ます', kana: 'きます', romaji: 'kimasu', meaning: 'Đến' }
    ]
  },

  {
    id: 'n5_verbs',
    courseId: 'jlpt5',
    name: 'Động từ N5 cơ bản',
    icon: '🏃',
    description: 'Các hành động thiết yếu trong bài thi JLPT N5',
    words: [
      { kanji: '会う', kana: 'あう', romaji: 'au', meaning: 'Gặp gỡ (bạn bè)' },
      { kanji: '開く', kana: 'あく', romaji: 'aku', meaning: 'Mở (cửa tự mở)' },
      { kanji: '遊ぶ', kana: 'あそぶ', romaji: 'asobu', meaning: 'Vui chơi, chơi đùa' },
      { kanji: '洗う', kana: 'あらう', romaji: 'arau', meaning: 'Rửa (tay, chén bát)' },
      { kanji: '歩く', kana: 'あるく', romaji: 'aruku', meaning: 'Đi bộ' },
      { kanji: '言う', kana: 'いう', romaji: 'iu', meaning: 'Nói' },
      { kanji: '歌う', kana: 'うたう', romaji: 'utau', meaning: 'Hát' },
      { kanji: '書く', kana: 'かく', romaji: 'kaku', meaning: 'Viết, vẽ' },
      { kanji: '貸す', kana: 'かす', romaji: 'kasu', meaning: 'Cho mượn / cho vay' },
      { kanji: '消す', kana: 'けす', romaji: 'kesu', meaning: 'Tắt (điện), xóa (bảng)' },
      { kanji: '知る', kana: 'しる', romaji: 'shiru', meaning: 'Biết' },
      { kanji: '吸う', kana: 'すう', romaji: 'suu', meaning: 'Hút (thuốc)' },
      { kanji: '住む', kana: 'すむ', romaji: 'sumu', meaning: 'Sinh sống / Cư trú' },
      { kanji: '立つ', kana: 'たつ', romaji: 'tatsu', meaning: 'Đứng lên' },
      { kanji: '使う', kana: 'つかう', romaji: 'tsukau', meaning: 'Sử dụng' },
      { kanji: '作る', kana: 'つくる', romaji: 'tsukuru', meaning: 'Chế tạo / Làm ra' },
      { kanji: '飛ぶ', kana: 'とぶ', romaji: 'tobu', meaning: 'Bay' },
      { kanji: '撮る', kana: 'とる', romaji: 'toru', meaning: 'Chụp (ảnh)' },
      { kanji: '脱ぐ', kana: 'ぬぐ', romaji: 'nugu', meaning: 'Cởi (quần áo, giày dép)' },
      { kanji: '入る', kana: 'はいる', romaji: 'hairu', meaning: 'Đi vào / bước vào' },
      { kanji: '話す', kana: 'はなす', romaji: 'hanasu', meaning: 'Trò chuyện / nói chuyện' },
      { kanji: '待つ', kana: 'まつ', romaji: 'matsu', meaning: 'Chờ đợi' },
      { kanji: '呼ぶ', kana: 'よぶ', romaji: 'yobu', meaning: 'Gọi (taxi, tên)' }
    ]
  },
  {
    id: 'n5_adjectives',
    courseId: 'jlpt5',
    name: 'Tính từ N5 thông dụng',
    icon: '🎨',
    description: 'Tính từ đuôi -i và đuôi -na cơ bản miêu tả tính chất',
    words: [
      { kanji: '大きい', kana: 'おおきい', romaji: 'ookii', meaning: 'Lớn, to' },
      { kanji: '小さい', kana: 'ちいさい', romaji: 'chiisai', meaning: 'Nhỏ, bé' },
      { kanji: '新しい', kana: 'あたらしい', romaji: 'atarashii', meaning: 'Mới' },
      { kanji: '古い', kana: 'ふるい', romaji: 'furui', meaning: 'Cũ' },
      { kanji: '良い', kana: 'いい / よい', romaji: 'ii / yoi', meaning: 'Tốt' },
      { kanji: '悪い', kana: 'わるい', romaji: 'warui', meaning: 'Xấu, tồi' },
      { kanji: '暑い', kana: 'あつい', romaji: 'atsui', meaning: 'Nóng (thời tiết)' },
      { kanji: '寒い', kana: 'さむい', romaji: 'samui', meaning: 'Lạnh (thời tiết)' },
      { kanji: '高い', kana: 'たかい', romaji: 'takai', meaning: 'Đắt / Cao' },
      { kanji: '安い', kana: 'やすい', romaji: 'yasui', meaning: 'Rẻ' },
      { kanji: '遠い', kana: 'とおい', romaji: 'tooi', meaning: 'Xa' },
      { kanji: '近い', kana: 'ちかい', romaji: 'chikai', meaning: 'Gần' },
      { kanji: '難しい', kana: 'むずかしい', romaji: 'muzukashii', meaning: 'Khó' },
      { kanji: '易しい', kana: 'やさしい', romaji: 'yasashii', meaning: 'Dễ / Hiền dịu' },
      { kanji: '甘い', kana: 'あまい', romaji: 'amai', meaning: 'Ngọt' },
      { kanji: '辛い', kana: 'からい', romaji: 'karai', meaning: 'Cay' },
      { kanji: '静か', kana: 'しずか', romaji: 'shizuka', meaning: 'Yên tĩnh (Tính từ đuôi -na)' },
      { kanji: '賑やか', kana: 'にぎやか', romaji: 'nigiyaka', meaning: 'Nhộn nhịp / Ồn ào (đuôi -na)' },
      { kanji: '親切', kana: 'しんせつ', romaji: 'shinsetsu', meaning: 'Thân thiện / Tốt bụng (đuôi -na)' },
      { kanji: '便利', kana: 'べんり', romaji: 'benri', meaning: 'Tiện lợi (đuôi -na)' },
      { kanji: '暇', kana: 'ひま', romaji: 'hima', meaning: 'Rảnh rỗi (đuôi -na)' }
    ]
  },
  {
    id: 'n5_nouns_daily',
    courseId: 'jlpt5',
    name: 'Đồ dùng & Sinh hoạt',
    icon: '🏠',
    description: 'Từ vựng về các đồ vật trong nhà và hoạt động hàng ngày',
    words: [
      { kanji: '鍵', kana: 'かぎ', romaji: 'kagi', meaning: 'Chìa khóa' },
      { kanji: '傘', kana: 'かさ', romaji: 'kasa', meaning: 'Cái ô / dù' },
      { kanji: '財布', kana: 'さいふ', romaji: 'saifu', meaning: 'Cái ví tiền' },
      { kanji: '写真', kana: 'しゃしん', romaji: 'shashin', meaning: 'Bức ảnh' },
      { kanji: '切符', kana: 'きっぷ', romaji: 'kippu', meaning: 'Vé (tàu, xe)' },
      { kanji: '車', kana: 'くるま', romaji: 'kuruma', meaning: 'Xe hơi / Ô tô' },
      { kanji: '自転車', kana: 'じてんしゃ', romaji: 'jitensha', meaning: 'Xe đạp' },
      { kanji: '飛行機', kana: 'ひこうき', romaji: 'hikouki', meaning: 'Máy bay' },
      { kanji: '服', kana: 'ふく', romaji: 'fuku', meaning: 'Quần áo' },
      { kanji: '靴下', kana: 'くつした', romaji: 'kutsushita', meaning: 'Đôi tất / vớ' },
      { kanji: '眼鏡', kana: 'めがね', romaji: 'megane', meaning: 'Kính mắt' },
      { kanji: '机', kana: 'つくえ', romaji: 'tsukue', meaning: 'Cái bàn học' },
      { kanji: '椅子', kana: 'いす', romaji: 'isu', meaning: 'Cái ghế' },
      { kanji: '窓', kana: 'まど', romaji: 'mado', meaning: 'Cửa sổ' },
      { kanji: '戸', kana: 'と', romaji: 'to', meaning: 'Cánh cửa chính' },
      { kanji: '石鹸', kana: 'せっけん', romaji: 'sekken', meaning: 'Xà phòng' },
      { kanji: '掃除', kana: 'そうじ', romaji: 'souji', meaning: 'Quét dọn / Vệ sinh' },
      { kanji: '洗濯', kana: 'せんたく', romaji: 'sentaku', meaning: 'Giặt giũ' },
      { kanji: '買い物', kana: 'かいもの', romaji: 'kaimono', meaning: 'Mua sắm' }
    ]
  },
  {
    id: 'n5_nouns_time',
    courseId: 'jlpt5',
    name: 'Thời gian & Địa điểm',
    icon: '🧭',
    description: 'Từ vựng chỉ thời gian, trạng thái và các địa điểm quen thuộc',
    words: [
      { kanji: '今日', kana: 'きょう', romaji: 'kyou', meaning: 'Hôm nay' },
      { kanji: '明日', kana: 'あした', romaji: 'ashita', meaning: 'Ngày mai' },
      { kanji: '昨日', kana: 'きのう', romaji: 'Hôm qua' },
      { kanji: '明後일', kana: 'あさって', romaji: 'asatte', meaning: 'Ngày kia' }, 
      { kanji: '一昨日', kana: 'おととい', romaji: 'ototoi', meaning: 'Hôm kia' },
      { kanji: '今週', kana: 'こんしゅう', romaji: 'konshuu', meaning: 'Tuần này' },
      { kanji: '来週', kana: 'raishuu', romaji: 'raishuu', meaning: 'Tuần sau' }, 
      { kanji: '先週', kana: 'せんしゅう', romaji: 'senshuu', meaning: 'Tuần trước' },
      { kanji: '今年', kana: 'ことし', romaji: 'kotoshi', meaning: 'Năm nay' },
      { kanji: '来年', kana: 'らいねん', romaji: 'rainen', meaning: 'Năm sau' },
      { kanji: '去年', kana: 'きょねん', romaji: 'kyonen', meaning: 'Năm ngoái' },
      { kanji: '部屋', kana: 'heya', romaji: 'heya', meaning: 'Căn phòng' }, 
      { kanji: '教室', kana: 'きょうしつ', romaji: 'kyoushitsu', meaning: 'Lớp học' },
      { kanji: '食堂', kana: 'しょくどう', romaji: 'shokudou', meaning: 'Nhà ăn / căng tin' },
      { kanji: '駅', kana: 'えき', romaji: 'eki', meaning: 'Nhà ga tàu hỏa' },
      { kanji: '交番', kana: 'こうばん', romaji: 'kouban', meaning: 'Bốt cảnh sát đầu phố' },
      { kanji: '橋', kana: 'はし', romaji: 'hashi', meaning: 'Cây cầu' },
      { kanji: '山', kana: 'やま', romaji: 'yama', meaning: 'Ngọn núi' },
      { kanji: '川', kana: 'かわ', romaji: 'kawa', meaning: 'Con sông' },
      { kanji: '庭', kana: 'にわ', romaji: 'niwa', meaning: 'Cái sân / mảnh vườn' }
    ]
  }
];

vocabularyCategories[5].words[3].kanji = '明後日';
vocabularyCategories[5].words[6].kanji = '来週';
vocabularyCategories[5].words[11].kanji = '部屋';

const referenceData = {
  numbers: [
    { label: '1', kana: 'いち', romaji: 'ichi', meaning: 'Một' },
    { label: '2', kana: 'に', romaji: 'ni', meaning: 'Hai' },
    { label: '3', kana: 'さん', romaji: 'san', meaning: 'Ba' },
    { label: '4', kana: 'よん / し', romaji: 'yon / shi', meaning: 'Bốn' },
    { label: '5', kana: 'ご', romaji: 'go', meaning: 'Năm' },
    { label: '6', kana: 'ろく', romaji: 'roku', meaning: 'Sáu' },
    { label: '7', kana: 'なな / しち', romaji: 'nana / shichi', meaning: 'Bảy' },
    { label: '8', kana: 'はち', romaji: 'hachi', meaning: 'Tám' },
    { label: '9', kana: 'きゅう / ku', romaji: 'kyuu / ku', meaning: 'Chín' },
    { label: '10', kana: 'じゅう', romaji: 'juu', meaning: 'Mười' },
    { label: '11', kana: 'じゅういち', romaji: 'juuichi', meaning: 'Mười một' },
    { label: '12', kana: 'じゅうに', romaji: 'juuni', meaning: 'Mười hai' },
    { label: '20', kana: 'にじゅう', romaji: 'nijuu', meaning: 'Hai mươi' },
    { label: '30', kana: 'さんじゅう', romaji: 'sanjuu', meaning: 'Ba mươi' },
    { label: '100', kana: 'ひゃく', romaji: 'hyaku', meaning: 'Một trăm' },
    { label: '200', kana: 'にひゃく', romaji: 'nihyaku', meaning: 'Hai trăm' },
    { label: '300', kana: 'さんびゃく', romaji: 'sanbyaku', meaning: 'Ba trăm (Biến âm)' },
    { label: '600', kana: 'ろっぴゃく', romaji: 'roppyaku', meaning: 'Sáu trăm (Biến âm)' },
    { label: '800', kana: 'はっぴゃく', romaji: 'happyaku', meaning: 'Tám trăm (Biến âm)' },
    { label: '1,000', kana: 'せん', romaji: 'sen', meaning: 'Một ngàn' },
    { label: '3,000', kana: 'さんぜん', romaji: 'sanzen', meaning: 'Ba ngàn (Biến âm)' },
    { label: '8,000', kana: 'はっせん', romaji: 'hassen', meaning: 'Tám ngàn (Biến âm)' },
    { label: '10,000', kana: 'いちまん', romaji: 'ichiman', meaning: 'Một vạn (Mười ngàn)' },
    { label: '100,000', kana: 'じゅうまん', romaji: 'juuman', meaning: 'Mười vạn (Trăm ngàn)' }
  ],
  calendar: [
    { label: 'Tháng 1', kana: 'いちがつ', romaji: 'ichigatsu', meaning: 'Tháng 1 (Tháng giêng)' },
    { label: 'Tháng 2', kana: 'にがつ', romaji: 'nigatsu', meaning: 'Tháng 2' },
    { label: 'Tháng 3', kana: 'さんがつ', romaji: 'sangatsu', meaning: 'Tháng 3' },
    { label: 'Tháng 4', kana: 'しがつ', romaji: 'shigatsu', meaning: 'Tháng 4 (Biến âm)' },
    { label: 'Tháng 5', kana: 'ごがつ', romaji: 'gogatsu', meaning: 'Tháng 5' },
    { label: 'Tháng 6', kana: 'ろくがつ', romaji: 'rokugatsu', meaning: 'Tháng 6' },
    { label: 'Tháng 7', kana: 'しちがつ', romaji: 'shichigatsu', meaning: 'Tháng 7 (Biến âm)' },
    { label: 'Tháng 8', kana: 'はちがつ', romaji: 'hachigatsu', meaning: 'Tháng 8' },
    { label: 'Tháng 9', kana: 'くがつ', romaji: 'kugatsu', meaning: 'Tháng 9 (Biến âm)' },
    { label: 'Tháng 10', kana: 'じゅうがつ', romaji: 'juugatsu', meaning: 'Tháng 10' },
    { label: 'Tháng 11', kana: 'じゅういちがつ', romaji: 'juuichigatsu', meaning: 'Tháng 11' },
    { label: 'Tháng 12', kana: 'じゅうにがつ', romaji: 'juunigatsu', meaning: 'Tháng 12' },
    { label: 'Thứ Hai', kana: 'げつようび', romaji: 'getsuyoubi', meaning: 'Thứ hai (Nguyệt diệu nhật)' },
    { label: 'Thứ Ba', kana: 'かようび', romaji: 'kayoubi', meaning: 'Thứ ba (Hỏa diệu nhật)' },
    { label: 'Thứ Tư', kana: 'すいようび', romaji: 'suiyoubi', meaning: 'Thứ tư (Thủy diệu nhật)' },
    { label: 'Thứ Năm', kana: 'もくようび', romaji: 'mokuyoubi', meaning: 'Thứ năm (Mộc diệu nhật)' },
    { label: 'Thứ Sáu', kana: 'きんようび', romaji: 'kinyoubi', meaning: 'Thứ sáu (Kim diệu nhật)' },
    { label: 'Thứ Bảy', kana: 'どようび', romaji: 'doyoubi', meaning: 'Thứ bảy (Thổ diệu nhật)' },
    { label: 'Chủ Nhật', kana: 'にちようび', romaji: 'nichiyoubi', meaning: 'Chủ nhật (Nhật diệu nhật)' },
    { label: 'Mùng 1', kana: 'ついたち', romaji: 'tsuitachi', meaning: 'Ngày mùng 1' },
    { label: 'Mùng 2', kana: 'ふつか', romaji: 'futsuka', meaning: 'Ngày mùng 2' },
    { label: 'Mùng 3', kana: 'みっか', romaji: 'mikka', meaning: 'Ngày mùng 3' },
    { label: 'Mùng 4', kana: 'よっか', romaji: 'yokka', meaning: 'Ngày mùng 4' },
    { label: 'Mùng 5', kana: 'いつか', romaji: 'itsuka', meaning: 'Ngày mùng 5' },
    { label: 'Mùng 6', kana: 'むいか', romaji: 'muika', meaning: 'Ngày mùng 6' },
    { label: 'Mùng 7', kana: 'なのか', romaji: 'nanoka', meaning: 'Ngày mùng 7' },
    { label: 'Mùng 8', kana: 'ようか', romaji: 'youka', meaning: 'Ngày mùng 8' },
    { label: 'Mùng 9', kana: 'ここのか', romaji: 'kokonoka', meaning: 'Ngày mùng 9' },
    { label: 'Mùng 10', kana: 'とおか', romaji: 'tooka', meaning: 'Ngày mùng 10' },
    { label: 'Ngày 14', kana: 'じゅうよっか', romaji: 'juuyokka', meaning: 'Ngày 14 (Biến âm)' },
    { label: 'Ngày 20', kana: 'はつか', romaji: 'hatsuka', meaning: 'Ngày 20 (Đặc biệt)' },
    { label: 'Ngày 24', kana: 'にじゅうよっか', romaji: 'nijuuyokka', meaning: 'Ngày 24 (Biến âm)' }
  ],
  counters: [
    { label: '1 cái', kana: 'ひとつ', romaji: 'hitotsu', meaning: 'Đếm đồ vật chung (~つ) - 1 cái' },
    { label: '2 cái', kana: 'ふたつ', romaji: 'futatsu', meaning: 'Đếm đồ vật chung - 2 cái' },
    { label: '3 cái', kana: 'みっつ', romaji: 'mittsu', meaning: 'Đếm đồ vật chung - 3 cái' },
    { label: '1 tờ', kana: 'いちまい', romaji: 'ichimai', meaning: 'Đếm vật mỏng dẹt (~枚) - 1 tấm, tờ, áo sơ mi' },
    { label: '2 tờ', kana: 'にまい', romaji: 'nimai', meaning: 'Đếm vật mỏng dẹt - 2 tấm, tờ, đĩa CD' },
    { label: '1 chai/lon', kana: 'いっぽん', romaji: 'ippon', meaning: 'Đếm vật dài thon (~本) - 1 chai, bút, ô, cây (Biến âm)' },
    { label: '2 chai/lon', kana: 'にほん', romaji: 'nihon', meaning: 'Đếm vật dài thon - 2 chai, lon, bút' },
    { label: '3 chai/lon', kana: 'さんぼん', romaji: 'sanbon', meaning: 'Đếm vật dài thon - 3 chai, lon (Biến âm)' },
    { label: '1 người', kana: 'ひとり', romaji: 'hitori', meaning: 'Đếm người (~人) - 1 người (Đặc biệt)' },
    { label: '2 người', kana: 'ふたり', romaji: 'futari', meaning: 'Đếm người - 2 người (Đặc biệt)' },
    { label: '3 người', kana: 'さんにん', romaji: 'sannin', meaning: 'Đếm người - 3 người' },
    { label: '4 người', kana: 'よにん', romaji: 'yonin', meaning: 'Đếm người - 4 người (Biến âm)' },
    { label: '1 con', kana: 'いっぴき', romaji: 'ippiki', meaning: 'Đếm thú nhỏ, cá, côn trùng (~匹) - 1 con (Biến âm)' },
    { label: '2 con', kana: 'ni-hiki', romaji: 'nihiki', meaning: 'Đếm động vật nhỏ - 2 con' },
    { label: '3 con', kana: 'さんびき', romaji: 'sanbiki', meaning: 'Đếm động vật nhỏ - 3 con (Biến âm)' }
  ],
  family: [
    { label: 'Gia đình mình', kana: 'かぞく', romaji: 'kazoku', meaning: 'Gia đình' },
    { label: 'Bố (mình)', kana: 'ちち', romaji: 'chichi', meaning: 'Bố' },
    { label: 'Mẹ (mình)', kana: 'haha', romaji: 'haha', meaning: 'Mẹ' },
    { label: 'Anh trai (mình)', kana: 'あに', romaji: 'ani', meaning: 'Anh trai' },
    { label: 'Chị gái (mình)', kana: 'あね', romaji: 'ane', meaning: 'Chị gái' },
    { label: 'Em trai (mình)', kana: 'おとうto', romaji: 'otouto', meaning: 'Em trai' },
    { label: 'Em gái (mình)', kana: 'いもうと', romaji: 'imouto', meaning: 'Em gái' },
    { label: 'Bố (người khác)', kana: 'おとうさん', romaji: 'otousan', meaning: 'Bố (khi gọi hoặc nói về bố người khác)' },
    { label: 'Mẹ (người khác)', kana: 'おかあさん', romaji: 'okaasan', meaning: 'Mẹ (khi gọi hoặc nói về mẹ người khác)' },
    { label: 'Anh trai (người khác)', kana: 'お兄さん (おにいさん)', romaji: 'oniisan', meaning: 'Anh trai (người khác)' },
    { label: 'Chị gái (người khác)', kana: 'お姉さん (おねえさん)', romaji: 'oneesan', meaning: 'Chị gái (người khác)' },
    { label: 'Em trai (người khác)', kana: '弟さん (おとうtoさん)', romaji: 'otoutosan', meaning: 'Em trai (người khác)' },
    { label: 'Em gái (người khác)', kana: '妹さん (いもうtoさん)', romaji: 'imoutosan', meaning: 'Em gái (người khác)' }
  ]
};

referenceData.counters[13].kana = 'にひき';
referenceData.family[5].kana = 'おとうto'.replace('to', 'と'); 
referenceData.family[11].kana = 'おとうとさん';
referenceData.family[12].kana = 'いもうとさん';
referenceData.family[11].romaji = 'otoutosan';
referenceData.family[12].romaji = 'imoutosan';
